-- Shared infrastructure
import ClassicalConstraints.Shared.Basic
import ClassicalConstraints.Shared.SideAMirror
import ClassicalConstraints.Shared.CookSelectorBridge
import ClassicalConstraints.Shared.CookFaithfulness
import ClassicalConstraints.Shared.SATPresheafCore
-- Chain 1: SAT / Cook-Levin (Paper B §3)
import ClassicalConstraints.Chain1_SAT.Observable
import ClassicalConstraints.Chain1_SAT.Basis
import ClassicalConstraints.Chain1_SAT.Descent
import ClassicalConstraints.Chain1_SAT.Obstruction
import ClassicalConstraints.Chain1_SAT.InfoTheory
import ClassicalConstraints.Chain1_SAT.Barriers
import ClassicalConstraints.Chain1_SAT.SelectionFunction
import ClassicalConstraints.Chain1_SAT.SelectionFunctionUniversality
import ClassicalConstraints.Chain1_SAT.ConcreteInstances
import ClassicalConstraints.Chain1_SAT.MorphismChain
import ClassicalConstraints.Chain1_SAT.EMDecomposition
import ClassicalConstraints.Chain1_SAT.DoubleNegationShapes
import ClassicalConstraints.Chain1_SAT.QuotientDescentCore
import ClassicalConstraints.Chain1_SAT.DescentBridgeConjecture
import ClassicalConstraints.Chain1_SAT.SheafObstruction
import ClassicalConstraints.Chain1_SAT.SATBoundaryLock
import ClassicalConstraints.Chain1_SAT.BridgeVacuity
import ClassicalConstraints.Chain1_SAT.SATDirectBridge
import ClassicalConstraints.Chain1_SAT.PartrecReflexive
import ClassicalConstraints.Chain1_SAT.StepIndexedEval
import ClassicalConstraints.Chain1_SAT.ReductionTheory
import ClassicalConstraints.Chain1_SAT.SATReduction
import ClassicalConstraints.Chain1_SAT.PolyTimeFromEvaln
-- Chain 2: Proof complexity (Paper B §4)
import ClassicalConstraints.Chain2_ProofComplexity.ResolutionWidthCore
import ClassicalConstraints.Chain2_ProofComplexity.CommunicationProtocolBridge
import ClassicalConstraints.Chain2_ProofComplexity.ResolutionProtocolExtraction
import ClassicalConstraints.Chain2_ProofComplexity.KrajicekExtraction
import ClassicalConstraints.Chain2_ProofComplexity.LiftingCore
import ClassicalConstraints.Chain2_ProofComplexity.FeasibleInterpolationBridge
import ClassicalConstraints.Chain2_ProofComplexity.ProofSearchBridge
import ClassicalConstraints.Chain2_ProofComplexity.ProofComplexityLock
import ClassicalConstraints.Chain2_ProofComplexity.ProofComplexityPartialLambek
import ClassicalConstraints.Chain2_ProofComplexity.ProofComplexityModelConcrete
-- Chain 3: Descriptive complexity (Paper B §5)
import ClassicalConstraints.Chain3_Descriptive.ESOWitnessCore
import ClassicalConstraints.Chain3_Descriptive.LocalityBridge
import ClassicalConstraints.Chain3_Descriptive.PebbleGameObstruction
import ClassicalConstraints.Chain3_Descriptive.FixedPointDefinabilityBridge
import ClassicalConstraints.Chain3_Descriptive.DescriptiveDepthBridge
import ClassicalConstraints.Chain3_Descriptive.DescriptiveComplexityLock
import ClassicalConstraints.Chain3_Descriptive.FOCanonicalForm
import ClassicalConstraints.Chain3_Descriptive.DescriptiveComplexityPartialLambek
import ClassicalConstraints.Chain3_Descriptive.DescriptiveComplexityModelConcrete
-- Chain 4: CSP / polymorphisms (Paper B §6)
import ClassicalConstraints.Chain4_CSP.CSPInstanceCore
import ClassicalConstraints.Chain4_CSP.PolymorphismCore
import ClassicalConstraints.Chain4_CSP.TractabilityDichotomy
import ClassicalConstraints.Chain4_CSP.WidthFromPolymorphisms
import ClassicalConstraints.Chain4_CSP.CSPSelectorBridge
import ClassicalConstraints.Chain4_CSP.CSPAlgebraLock
import ClassicalConstraints.Chain4_CSP.CSPDirectBridge
-- Chain 5: Algebraic proof complexity (Paper B §7)
import ClassicalConstraints.Chain5_Algebraic.PolynomialCalculusCore
import ClassicalConstraints.Chain5_Algebraic.NullstellensatzCore
import ClassicalConstraints.Chain5_Algebraic.SOSRankCore
import ClassicalConstraints.Chain5_Algebraic.DegreeLowerBoundBridge
import ClassicalConstraints.Chain5_Algebraic.AlgebraicSearchBridge
import ClassicalConstraints.Chain5_Algebraic.AlgebraicProofLock
import ClassicalConstraints.Chain5_Algebraic.MultilinearReductionConcrete
import ClassicalConstraints.Chain5_Algebraic.AlgebraicModelConcrete
-- Chain 6: Extension complexity (Paper B §8)
import ClassicalConstraints.Chain6_Extension.SlackMatrixCore
import ClassicalConstraints.Chain6_Extension.NonnegRankObstruction
import ClassicalConstraints.Chain6_Extension.SATPolytopeCore
import ClassicalConstraints.Chain6_Extension.ExtensionSelectorBridge
import ClassicalConstraints.Chain6_Extension.ExtensionComplexityLock
import ClassicalConstraints.Chain6_Extension.DirectBridgeAnalysis
-- Chain 7: Distributed protocols (Paper B §9)
import ClassicalConstraints.Chain7_Protocol.DistributedWitnessCore
import ClassicalConstraints.Chain7_Protocol.CapabilityWitnessInstance
import ClassicalConstraints.Chain7_Protocol.ConsensusWitnessInstance
import ClassicalConstraints.Chain7_Protocol.ZKProjectionInstance
import ClassicalConstraints.Chain7_Protocol.CoherenceTransportMeasure
import ClassicalConstraints.Chain7_Protocol.ValueCollapseInstance
import ClassicalConstraints.Chain7_Protocol.ProtocolWitnessFamilyLock
import ClassicalConstraints.Chain3_Descriptive.BridgeVacuity
import ClassicalConstraints.Chain4_CSP.BridgeVacuity
import ClassicalConstraints.Chain5_Algebraic.BridgeVacuity
import ClassicalConstraints.Chain6_Extension.BridgeVacuity
import ClassicalConstraints.Chain7_Protocol.BridgeVacuity
import ClassicalConstraints.Chain7_Protocol.ProtocolDirectBridge
-- Concrete encodings (research frontier)
import ClassicalConstraints.ConcreteEncodings.DirectVariableEncoding
import ClassicalConstraints.ConcreteEncodings.CapabilityDelegationEncoding
